/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRobloxSearchRouteImport } from './routes/api/roblox-search'
import { Route as ApiFriendsRouteImport } from './routes/api/friends'
import { Route as ApiUserUsernameRouteImport } from './routes/api/user.$username'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRobloxSearchRoute = ApiRobloxSearchRouteImport.update({
  id: '/api/roblox-search',
  path: '/api/roblox-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFriendsRoute = ApiFriendsRouteImport.update({
  id: '/api/friends',
  path: '/api/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserUsernameRoute = ApiUserUsernameRouteImport.update({
  id: '/api/user/$username',
  path: '/api/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/friends': typeof ApiFriendsRoute
  '/api/roblox-search': typeof ApiRobloxSearchRoute
  '/api/user/$username': typeof ApiUserUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/friends': typeof ApiFriendsRoute
  '/api/roblox-search': typeof ApiRobloxSearchRoute
  '/api/user/$username': typeof ApiUserUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/friends': typeof ApiFriendsRoute
  '/api/roblox-search': typeof ApiRobloxSearchRoute
  '/api/user/$username': typeof ApiUserUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/friends'
    | '/api/roblox-search'
    | '/api/user/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api/friends'
    | '/api/roblox-search'
    | '/api/user/$username'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/friends'
    | '/api/roblox-search'
    | '/api/user/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiFriendsRoute: typeof ApiFriendsRoute
  ApiRobloxSearchRoute: typeof ApiRobloxSearchRoute
  ApiUserUsernameRoute: typeof ApiUserUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roblox-search': {
      id: '/api/roblox-search'
      path: '/api/roblox-search'
      fullPath: '/api/roblox-search'
      preLoaderRoute: typeof ApiRobloxSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/friends': {
      id: '/api/friends'
      path: '/api/friends'
      fullPath: '/api/friends'
      preLoaderRoute: typeof ApiFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/$username': {
      id: '/api/user/$username'
      path: '/api/user/$username'
      fullPath: '/api/user/$username'
      preLoaderRoute: typeof ApiUserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiFriendsRoute: ApiFriendsRoute,
  ApiRobloxSearchRoute: ApiRobloxSearchRoute,
  ApiUserUsernameRoute: ApiUserUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
